#
# Copyright (C) 2020-2021 Alexandros Theodotou <alex at zrythm dot org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

trigger:
- master
- develop
- bugfixes

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Make
    timeoutInMinutes: 120
    steps:
    - script: |
        set -e
        echo "updating brew"
        brew update || true
        echo "installing deps"
        # use || true because it returns 1
        brew install gnu-sed fftw meson libsamplerate sdl2 chromaprint libgtop lilv librsvg adwaita-icon-theme guile gtksourceview5 graphviz zstd npm rt-audio rtmidi jack qjackctl cmake help2man xxhash vamp-plugin-sdk json-glib || true
        echo "linking python"
        brew link --overwrite python
        #npm install -g appdmg
        echo "installing cmake"
        pip3 install scikit-build
        pip3 install cmake
      displayName: 'Install deps'

    - script: |
        git clone https://git.sr.ht/~alextee/zrythm
        git clone https://github.com/mesonbuild/meson
      displayName: 'Clone repos'

    - script: |
        cd /Users/runner/work/1/s
        mv VERSION VERSION.txt
        gsed -i "s|'VERSION'|'VERSION.txt'|" meson.build
        meson build -Dtests=true -Dgtk4:x11-backend=false
        mv subprojects/libaudec/VERSION subprojects/libaudec/VERSION.txt
        gsed -i "s|'VERSION'|'VERSION.txt'|" subprojects/libaudec/meson.build
        ninja -C build
      displayName: 'Configure and build'

    - script: |
        cd s
        meson test -C build || cat build/meson-logs/testlog.txt
      displayName: 'Test'

    - script: |
        cd s
        ninja -C build install
      displayName: 'Install'
